#---------------------------------------------------------------
# Informação
# autor: Leonardo Viana Pereira
# cargo: ANalista de DevOps
# Empresa: It happens
# email: leonardo.viana@armateus.com.br
# version: 0.1.0
# Descrição: Testar o redmine
# Ferramenta para gerenciamento de progetos
# http://localhost:8080
#---------------------------------------------------------------

version: '3.1'

services:

  redmine:
    image: redmine
    restart: always
    ports:
      - 8080:3000
    environment:
      REDMINE_DB_MYSQL: db
      REDMINE_DB_PASSWORD: ithappens
      REDMINE_SECRET_KEY_BASE: ithappens

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ithappens
      MYSQL_DATABASE: redmine